### ISSUE TITLE
RTE1 and RTE2 do not play on Windows 10

### ISSUE THREAD

**Issue by ianbrk** [zakalibit/kodi.rteplayer.hq#1]
Hello, I am running Windows 10, Kodi 16.0. RTE News, RTE1, and RTE2 show up under the Live category. RTE News plays fine. Non-live content plays fine as well.

Here are my logs when I attempt to play RTE1 or RTE2.

```
09:19:17 T:16372   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:7001/rte1-576
09:19:17 T:16372  NOTICE: DVDPlayer: Opening: http://127.0.0.1:7001/rte1-576
09:19:17 T:16372 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
09:19:17 T:11080  NOTICE: Creating InputStream
09:19:19 T:11080   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:7001/rte1-576
09:19:29 T:11080   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
09:19:29 T:11080   ERROR: CCurlFile::Open failed with code 0 for http://127.0.0.1:7001/rte1-576
09:19:29 T:11080   ERROR: XFILE::CFileCache::Open - failed to open source <http://127.0.0.1:7001/rte1-576>
09:19:29 T:11080   ERROR: CDVDPlayer::OpenInputStream - error opening [http://127.0.0.1:7001/rte1-576]
09:19:29 T:11080  NOTICE: CDVDPlayer::OnExit()
09:19:29 T:16372   ERROR: Playlist Player: skipping unplayable item: 0, path [http://127.0.0.1:7001/rte1-576]
09:19:29 T:16372  NOTICE: CDVDPlayer::CloseFile()
09:19:29 T:16372  NOTICE: DVDPlayer: waiting for threads to exit
09:19:29 T:16372  NOTICE: DVDPlayer: finished waiting
09:19:29 T:16372  NOTICE: CDVDPlayer::CloseFile()
09:19:29 T:16372  NOTICE: DVDPlayer: waiting for threads to exit
09:19:29 T:16372  NOTICE: DVDPlayer: finished waiting
09:19:32 T:16372   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:7001/rte2-576
09:19:32 T:16372  NOTICE: DVDPlayer: Opening: http://127.0.0.1:7001/rte2-576
09:19:32 T:16372 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
09:19:32 T:14172  NOTICE: Creating InputStream
09:19:33 T:14172   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:7001/rte2-576
09:19:43 T:14172   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
09:19:43 T:14172   ERROR: CCurlFile::Open failed with code 0 for http://127.0.0.1:7001/rte2-576
09:19:43 T:14172   ERROR: XFILE::CFileCache::Open - failed to open source <http://127.0.0.1:7001/rte2-576>
09:19:43 T:14172   ERROR: CDVDPlayer::OpenInputStream - error opening [http://127.0.0.1:7001/rte2-576]
09:19:43 T:14172  NOTICE: CDVDPlayer::OnExit()
09:19:43 T:16372   ERROR: Playlist Player: skipping unplayable item: 0, path [http://127.0.0.1:7001/rte2-576]
09:19:43 T:16372  NOTICE: CDVDPlayer::CloseFile()
09:19:43 T:16372  NOTICE: DVDPlayer: waiting for threads to exit
09:19:43 T:16372  NOTICE: DVDPlayer: finished waiting
09:19:43 T:16372  NOTICE: CDVDPlayer::CloseFile()
09:19:43 T:16372  NOTICE: DVDPlayer: waiting for threads to exit
09:19:43 T:16372  NOTICE: DVDPlayer: finished waiting
```

**Comment by zakalibit** [comment]
Wont work on windows, RTE1 and RTE2 show up because you have either ffmpeg.exe, or avconv.exe on the path, however stream decrypring service is not started as it does not find pycrypto.

**Comment by ianbrk** [comment]
I'm not home to test this but would installing these Windows binaries for pycrypto solve that problem, you think?
http://www.voidspace.org.uk/python/modules.shtml#pycrypto

**Comment by ianbrk** [comment]
I just tested that myself and it did not work. Ah, well. Any ideas for possible future support for Windows?

**Comment by zakalibit** [comment]
I have it somewhat working, there is 2 problems at the moment:
- ffmpeg process starts in a cmd windows (experimented with few options in subprocess.Popen win no success so far)
- kodi shutdown hangs, again process kill() on linux works just fine, on windows does not

**Comment by ianbrk** [comment]
The first problem could probably be solved by a utility like RunHiddenConsole.exe. Try it [here](http://redmine.lighttpd.net/attachments/660/RunHiddenConsole.zip). Just pass the path to ffmpeg as an argument, etc.

**Comment by zakalibit** [comment]
Actually I found a solution to that as we speak, shutdown is still a problem, well it is mainly a problem if you stop live streaming and exit immediately, or exist while streaming

**Comment by ianbrk** [comment]
Sounds like it has trouble shutting down a subprocess. I don't know how Kodi performs it's shut down procedure but it's Plex and Steam don't shut down until every single subprocess is shut down properly. So if a subprocess crashes but still appears as running in the Task Manager it will hang.

**Comment by zakalibit** [comment]
No I use python's subprocess.Popen module

**Comment by ianbrk** [comment]
[This person on StackOverflow](http://stackoverflow.com/questions/22021701/kill-the-popen-child-process) ended up writing the TaskList to a text file, filtering out the process to shut down, parsing out the PID and sending a SIGTERM signal through the kill() function.

Maybe the PID you are trying to kill is not the one that is actually running?

**Comment by zakalibit** [comment]
I just pushed plugin.video.rteplayer.hq-2.2.0.zip it works on kodi Jarvis

**Comment by ianbrk** [comment]
Works great. Much appreciated. I will close this now.
